name: filestack-drag-and-drop-js-stg
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository env
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: "https://registry.npmjs.org"
        scope: '@filestack'
    - name: Install deps
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
    - name: Build code
      run: npm run build
    - name: Publush to NPM (only on tag)
      if: startsWith(github.ref, 'refs/tags/') && success()
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish package to cdn
      run: npm run deploy:beta
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: Slack Message Done
      uses: act10ns/slack@v1.2.2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_STG }}
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#deploys-stg'
